###################################################
# +---------------------------------------------+ #
# |             Database Connection             | #
# +---------------------------------------------+ #
###################################################

# CAUTION! Developer mode will drop all database tables on startup. DO NOT USE IN PRODUCTION.
developer-mode: false

# Database connection settings.
mysql:
  host: localhost
  port: 3306
  username: unitedregions
  password: unitedregions
  database: unitedregions

general:

  # Scale multiplier for the import SVG
  import-scale: 1
  # Offsets to be subtracted from the imported vertex positions. These will usually be 
  # half of the map width / height
  import-offset-x: 0
  import-offset-y: 0

  region-chunk-size: 8
  # Colours as int values (e.g. https://argb-int-calculator.netlify.app/)

  protect-unclaimed-land: true

  allow-town-claims-outside-home-region: false

  # Default map colors & styles

  country-default-stroke-colour: -13399809
  country-default-fill-colour: 540248319
  country-default-stroke-width: 5

  region-default-stroke-colour: 536870912
  region-default-fill-colour: 0
  region-default-stroke-width: 2
  region-default-dash: "1"

  region-country-stroke-width: 1
  region-country-dash: "4,4"

  settlement-default-fill-colour: 540787967
  settlement-default-stroke-colour: -13399809
  settlement-default-stroke-width: 2
  settlement-default-dash: "1"

  settlement-country-stroke-colour: -1073741824
  settlement-country-fill-colour: 540248319
  settlement-country-stroke-width: 2
  settlement-country-dash: "4,4"

economy:
  new-settlement-cost: 8000
  settlement-claim-base-cost: 48
  # Available vars: base (base costs), claims (total settlement claim count).
  settlement-claim-cost-progression: "base + ((claims - 1)^2 * 0.005)"
  # Available vars: base (base costs), claims (total settlement claim count), residents (total resident count). This value will be multiplied by the number of settlement chunks.
  settlement-base-upkeep-per-plot: 6
  settlement-upkeep-per-plot-formula: "base * (0.1 * (claims / 25) + 1.0) / (0.4 * (residents / 2.0) + 1.0)"

  settlement-tax-min-percent: 0.0
  settlement-tax-max-percent: 0.2
  settlement-tax-min-amount: 0.0
  settlement-tax-max-amount: 1500.0

  new-country-cost: 80000
  region-claim-base-cost: 80000
  # Available vars: base (base costs), regions (total country region count), distance (Euclidean distance to capital home chunk in blocks).
  region-claim-cost-modifier: "base + (base * ((regions + 1) * 0.5) * (distance / 1000) * 0.25)"

protection:
  containers:
    - CHEST
    - TRAPPED_CHEST
    - ENDER_CHEST
    - BARREL
    - COPPER_CHEST
    - EXPOSED_COPPER_CHEST
    - WEATHERED_COPPER_CHEST
    - OXIDIZED_COPPER_CHEST
    - WAXED_COPPER_CHEST
    - WAXED_EXPOSED_COPPER_CHEST
    - WAXED_WEATHERED_COPPER_CHEST
    - WAXED_OXIDIZED_COPPER_CHEST
  use-blocks:
    - CRAFTING_TABLE
    - SMITHING_TABLE
    - ENCHANTING_TABLE
    - FLETCHING_TABLE
    - FURNACE
    - BLAST_FURNACE
    - CARTOGRAPHY_TABLE
    - BREWING_STAND
  switch-tags: # Minecraft material tags
    - doors
    - trapdoors
    - buttons
  switch-blocks:
    - LEVER
  interact:
    - VILLAGER
    - COW
    - SHEEP
  monsters:
    - ZOMBIE
    - ZOMBIE_VILLAGER
    - HUSK
    - SKELETON
    - CREEPER
    - SPIDER
    - CAVE_SPIDER
    - SLIME
    - PARCHED
    - DROWNED
    - PHANTOM
    - PILLAGER
    - RAVAGER
    - VINDICATOR
    - ENDERMAN
  animals:
    - CHICKEN
    - COW
    - SHEEP
    - PIG

settlement-chunks:
  none:
    map-icon: "+"
    map-icon-color: "§7"
    max-per-settlement: -1
  fortress:
    map-icon: "F"
    map-icon-color: "§f"
    max-per-settlement: 1
