name: UnitedLands
version: 0.0.1
main: org.unitedlands.unitedlands.UnitedLands
api-version: 1.18
description: UnitedLands Core claiming and geopol plugin
author: Theriel_
depend: [ UnitedLib ]
softdepend: [ Vault, Pl3xmap, Towny, PlaceholderAPI ]